### ISSUE TITLE
Adding an image tag

### ISSUE THREAD

**Issue by Sangdol** [yogthos/clj-rss#18]
Hello, 

Thanks for building this library.

I'm trying to figure out how I can put [an image tag](https://validator.w3.org/feed/docs/rss2.html#ltimagegtSubelementOfLtchannelgt) in the RSS.

To add an image tag I need to be able to add a nested tag but I couldn't figure out how I can do it.

I've tried something like this
```clojure
(rss/channel-xml {:title       blog-title
                  :link        base-url
                  :description description
                  :image {:url (cdata blog-image-url)
                          :title (cdata blog-title)
                          :link  blog-url}}
                items)
```

but I've faced an error 
```
Caused by: clojure.lang.ExceptionInfo: Auto-generating prefixes is not supported for content-qnames. Please declare all URIs used in content qnames. {:qname :url, :uri ""}
	at clojure.data.xml.jvm.emit$prefix_for.invokeStatic(emit.clj:47)
	at clojure.data.xml.jvm.emit$prefix_for.invoke(emit.clj:45)
	at clojure.data.xml.jvm.emit$eval6876$fn__6878.invoke(emit.clj:158)
	at clojure.data.xml.jvm.emit$eval6800$fn__6801$G__6791__6810.invoke(emit.clj:34)
	at clojure.data.xml.jvm.emit$write_document$fn__6913.invoke(emit.clj:212)
	at clojure.core.protocols$fn__8144.invokeStatic(protocols.clj:168)
	at clojure.core.protocols$fn__8144.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__8099$G__8094__8108.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__8131.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__8131.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__8073$G__8068__8086.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6828)
	at clojure.core$reduce.invoke(core.clj:6810)
	at clojure.data.xml.jvm.emit$write_document.invokeStatic(emit.clj:212)
	at clojure.data.xml.jvm.emit$write_document.invoke(emit.clj:196)
	at clojure.data.xml$emit.invokeStatic(xml.clj:141)
	at clojure.data.xml$emit.doInvoke(xml.clj:135)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invokeStatic(core.clj:669)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.data.xml$emit_str.invokeStatic(xml.clj:150)
	at clojure.data.xml$emit_str.doInvoke(xml.clj:143)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clj_rss.core$channel_xml.invokeStatic(core.clj:149)
	at clj_rss.core$channel_xml.doInvoke(core.clj:146)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
```

Could I add an image tag? 

Thanks.

**Comment by yogthos** [comment]
Hmm, it looks clojure.data.xml doesn't like the uri. Could you provide what `(cdata blog-image-url)` ends up generating?

**Comment by Sangdol** [comment]
Thanks for the answer, Dmitri. It seems it throws an error regardless of the uri value.

I've created a branch with a reproducible code so that you can take a look.

https://github.com/Sangdol/clj-rss/blob/rss-image-tag/test/clj_rss/core_test.clj#L7

**Comment by Sangdol** [comment]
Thanks for the fix. It works well.

I just found one interesting thing that I don't understand why it's happening.

When I generate an image tag with cdata contents only the one in the `url` tag gets escaped. It's okay in my use case but I believe this is not the right behavior. 

```clojure
{:type  :image
 :url   (cdata "url")
 :title (cdata "title")
 :link  (cdata "link")}
```

```xml
<image>
    <url>&lt;![CDATA[ url ]]&gt;</url>
    <title><![CDATA[ title ]]></title>
    <link><![CDATA[ link ]]></link>
</image>
```

**Comment by yogthos** [comment]
That's actually the expected behavior currently. When the tags are generated, the following function is called:

```clojure
(defn- make-tags [tags]
  (flatten
    (for [[k v] (seq tags)]
      (cond
        (and (coll? v) (map? (first v)))
        (apply-macro clj-rss.core/tag (into [k] v))
        (coll? v)
        (map (fn [v] (make-tags {k v})) v)
        :else
        (tag k (cond
                 (some #{k} [:pubDate :lastBuildDate]) (format-time v)
                 (some #{k} [:description :title :link :author]) (xml-str v)
                 :else v))))))
```

It will call `xml-str` function on `:description`, `:title`, `:link`, and `:author` tags. This function looks as follows:

```clojure
(defn- xml-str
  "Returns a value suitable for inclusion as an XML element. If the string
  is wrapped in <![CDATA[ ... ]]>, remove the tags and wrap in a CData record"
  [^String s]
  (if (and (.startsWith s "<![CDATA[")
           (.endsWith s "]]>"))
    (-> s
        (.replace "<![CDATA[" "")
        (.replace "]]>" "")
        cdata)
    s))
```

It checks if the string starts with `<![CDATA[` and ends with `]]>`, when that's the case the string is assumed to be a CDATA tag and it's wrapped with a call to `cdata` with the tags stripped. Otherwise, it will be left alone. Since you're calling `cdata` explicitly before passing the data in, it ends up being unprocessed and gets escaped. Since `:url` is not one of the keys that triggers `xml-str` wrapping, it's left alone and then escaped when XML is generated.

If you call `channel` function instead of `channel-xml`, you can see the intermediate structure that gets serialized to XML:

```clojure
(channel
          {:title "foo" :link "http://foo" :description "bar"}
          {:type  :image
           :title "<![CDATA[ title ]]>"
           :url   "<![CDATA[ url ]]>"
           :link  "<![CDATA[ link ]]>"})

{:tag     :rss,
         :attrs   {:version "2.0", "xmlns:atom" "http://www.w3.org/2005/Atom"},
         :content [{:tag     :channel,
                    :attrs   nil,
                    :content [{:tag "atom:link", :attrs {:href "http://foo", :rel "self", :type "application/rss+xml"}}
                              {:content ["foo"], :attrs nil, :tag :title}
                              {:content ["http://foo"], :attrs nil, :tag :link}
                              {:content ["bar"], :attrs nil, :tag :description}
                              {:content ["clj-rss"], :attrs nil, :tag :generator}
                              {:tag     :image,
                               :attrs   nil,
                               :content [{:content [#clojure.data.xml.node.CData{:content " title "}], :attrs nil, :tag :title}
                                         {:content ["<![CDATA[ url ]]>"], :attrs nil, :tag :url}
                                         {:content [#clojure.data.xml.node.CData{:content " link "}], :attrs nil, :tag :link}]}]}]}
```

**Comment by Sangdol** [comment]
Okay, I actually didn't exactly understand that [there's no difference between CDATA and escaping when the value is actually used](https://stackoverflow.com/questions/967420/when-to-cdata-vs-escape-vice-versa). It looks good and you can merge the PR and close the ticket. Thanks a lot for the answers and the fix.

**Comment by yogthos** [comment]
great, just pushed out `0.2.6` with the fix.
